const tasks = [
  {
    id: 1,
    title: "Implement user authentication",
    status: "In Progress",
    assignee: "Alice",
    dueDate: "2024-08-20",
  },
  {
    id: 2,
    title: "Create dashboard layout",
    status: "Pending",
    assignee: "Bob",
    dueDate: "2024-08-22",
  },
  {
    id: 3,
    title: "Integrate API for user data",
    status: "Completed",
    assignee: "Charlie",
    dueDate: "2024-08-18",
  },
  {
    id: 4,
    title: "Optimize data fetching",
    status: "In Progress",
    assignee: "Alice",
    dueDate: "2024-08-25",
  },
  {
    id: 5,
    title: "Design responsive UI",
    status: "Pending",
    assignee: "Bob",
    dueDate: "2024-08-30",
  },
  {
    id: 6,
    title: "Implement data visualization",
    status: "In Progress",
    assignee: "Charlie",
    dueDate: "2024-08-28",
  },
  {
    id: 7,
    title: "Fix bugs in user profile page",
    status: "Pending",
    assignee: "Alice",
    dueDate: "2024-08-21",
  },
  {
    id: 8,
    title: "Add pagination to tables",
    status: "Completed",
    assignee: "Bob",
    dueDate: "2024-08-19",
  },
  {
    id: 9,
    title: "Implement search functionality",
    status: "In Progress",
    assignee: "Charlie",
    dueDate: "2024-08-24",
  },
  {
    id: 10,
    title: "Create reusable components",
    status: "Pending",
    assignee: "Alice",
    dueDate: "2024-08-27",
  },
  {
    id: 11,
    title: "Set up unit tests",
    status: "Completed",
    assignee: "Bob",
    dueDate: "2024-08-23",
  },
  {
    id: 12,
    title: "Implement dark mode",
    status: "In Progress",
    assignee: "Charlie",
    dueDate: "2024-08-26",
  },
  {
    id: 13,
    title: "Optimize bundle size",
    status: "Pending",
    assignee: "Alice",
    dueDate: "2024-08-29",
  },
  {
    id: 14,
    title: "Integrate error tracking",
    status: "Completed",
    assignee: "Bob",
    dueDate: "2024-08-20",
  },
  {
    id: 15,
    title: "Implement role-based access control",
    status: "In Progress",
    assignee: "Charlie",
    dueDate: "2024-08-22",
  },
  {
    id: 16,
    title: "Create user settings page",
    status: "Pending",
    assignee: "Alice",
    dueDate: "2024-08-25",
  },
  {
    id: 17,
    title: "Add loading spinners",
    status: "Completed",
    assignee: "Bob",
    dueDate: "2024-08-18",
  },
  {
    id: 18,
    title: "Implement file upload",
    status: "In Progress",
    assignee: "Charlie",
    dueDate: "2024-08-28",
  },
  {
    id: 19,
    title: "Optimize image loading",
    status: "Pending",
    assignee: "Alice",
    dueDate: "2024-08-30",
  },
  {
    id: 20,
    title: "Create notifications system",
    status: "Completed",
    assignee: "Bob",
    dueDate: "2024-08-21",
  },
  {
    id: 21,
    title: "Implement data export",
    status: "In Progress",
    assignee: "Charlie",
    dueDate: "2024-08-24",
  },
  {
    id: 22,
    title: "Fix CSS issues in IE11",
    status: "Pending",
    assignee: "Alice",
    dueDate: "2024-08-27",
  },
  {
    id: 23,
    title: "Add tooltips to icons",
    status: "Completed",
    assignee: "Bob",
    dueDate: "2024-08-23",
  },
  {
    id: 24,
    title: "Implement drag-and-drop",
    status: "In Progress",
    assignee: "Charlie",
    dueDate: "2024-08-26",
  },
  {
    id: 25,
    title: "Create custom hooks",
    status: "Pending",
    assignee: "Alice",
    dueDate: "2024-08-29",
  },
  {
    id: 26,
    title: "Optimize form validation",
    status: "Completed",
    assignee: "Bob",
    dueDate: "2024-08-20",
  },
  {
    id: 27,
    title: "Implement multi-language support",
    status: "In Progress",
    assignee: "Charlie",
    dueDate: "2024-08-22",
  },
  {
    id: 28,
    title: "Create user activity log",
    status: "Pending",
    assignee: "Alice",
    dueDate: "2024-08-25",
  },
  {
    id: 29,
    title: "Add keyboard shortcuts",
    status: "Completed",
    assignee: "Bob",
    dueDate: "2024-08-18",
  },
  {
    id: 30,
    title: "Implement real-time updates",
    status: "In Progress",
    assignee: "Charlie",
    dueDate: "2024-08-28",
  },
  {
    id: 31,
    title: "Optimize database queries",
    status: "Pending",
    assignee: "Alice",
    dueDate: "2024-08-30",
  },
  {
    id: 32,
    title: "Create admin dashboard",
    status: "Completed",
    assignee: "Bob",
    dueDate: "2024-08-21",
  },
  {
    id: 33,
    title: "Implement caching strategy",
    status: "In Progress",
    assignee: "Charlie",
    dueDate: "2024-08-24",
  },
  {
    id: 34,
    title: "Fix accessibility issues",
    status: "Pending",
    assignee: "Alice",
    dueDate: "2024-08-27",
  },
  {
    id: 35,
    title: "Add user avatars",
    status: "Completed",
    assignee: "Bob",
    dueDate: "2024-08-23",
  },
  {
    id: 36,
    title: "Implement session management",
    status: "In Progress",
    assignee: "Charlie",
    dueDate: "2024-08-26",
  },
  {
    id: 37,
    title: "Create custom error pages",
    status: "Pending",
    assignee: "Alice",
    dueDate: "2024-08-29",
  },
  {
    id: 38,
    title: "Optimize network requests",
    status: "Completed",
    assignee: "Bob",
    dueDate: "2024-08-20",
  },
  {
    id: 39,
    title: "Implement feature flags",
    status: "In Progress",
    assignee: "Charlie",
    dueDate: "2024-08-22",
  },
  {
    id: 40,
    title: "Create user feedback form",
    status: "Pending",
    assignee: "Alice",
    dueDate: "2024-08-25",
  },
  {
    id: 41,
    title: "Add breadcrumbs navigation",
    status: "Completed",
    assignee: "Bob",
    dueDate: "2024-08-18",
  },
  {
    id: 42,
    title: "Implement data import",
    status: "In Progress",
    assignee: "Charlie",
    dueDate: "2024-08-28",
  },
  {
    id: 43,
    title: "Optimize CSS for performance",
    status: "Pending",
    assignee: "Alice",
    dueDate: "2024-08-30",
  },
  {
    id: 44,
    title: "Create user onboarding flow",
    status: "Completed",
    assignee: "Bob",
    dueDate: "2024-08-21",
  },
  {
    id: 45,
    title: "Implement two-factor authentication",
    status: "In Progress",
    assignee: "Charlie",
    dueDate: "2024-08-24",
  },
  {
    id: 46,
    title: "Fix layout issues on mobile",
    status: "Pending",
    assignee: "Alice",
    dueDate: "2024-08-27",
  },
  {
    id: 47,
    title: "Add support for dark mode",
    status: "Completed",
    assignee: "Bob",
    dueDate: "2024-08-23",
  },
  {
    id: 48,
    title: "Implement push notifications",
    status: "In Progress",
    assignee: "Charlie",
    dueDate: "2024-08-26",
  },
  {
    id: 49,
    title: "Create custom themes",
    status: "Pending",
    assignee: "Alice",
    dueDate: "2024-08-29",
  },
  {
    id: 50,
    title: "Optimize app for SEO",
    status: "Completed",
    assignee: "Bob",
    dueDate: "2024-08-20",
  },
];

export default tasks;
